### ISSUE TITLE
Could we change the readme to adjust the values.yaml and use helm for the adjustments?

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/caasp-monitoring#8]
kubectl edit is not a  good practice for deployments done via helm - so it would be nice if we could get the readme changed to give the right advice on how to adjust the values.yaml for the helm based deployment and then update the config with

i.e. I believe like this in the server section of the values.yaml:

```
  ## Additional Prometheus server Secret mounts
  # Defines additional mounts with secrets. Secrets must be manually created in the namespace.
  extraSecretMounts:
    - name: etcd-certs
      mountPath: /etc/secrets
    #  subPath: ""
      secretName: etcd-certs
      readOnly: true
```

And then 

`helm upgrade prometheus prometheus-9.3.3.tgz -f prometheus-9.3.3.values.yaml`
